[server]
headless = true
enableCORS = true
enableXsrfProtection = true

[theme]
primaryColor="#3498db"
backgroundColor="#ffffff"
secondaryBackgroundColor="#f8f9fa"
textColor="#333333"

[logger]
level = "info"

[client]
showErrorDetails = true
toolbarMode = "developer"
