# Streamlit secrets configuration file
# ⚠️ WARNING: This file is for LOCAL DEVELOPMENT ONLY
# These values are automatically loaded into st.secrets in local development
# For deployment to Streamlit Cloud, use the Streamlit Cloud secrets manager
# https://docs.streamlit.io/streamlit-cloud/get-started/deploy-an-app/connect-to-data-sources/secrets-management

[openai]
# Replace with your actual API key for local development
# api_key = "your_openai_api_key_here"
